### ISSUE TITLE
bombcrypto-superbot/build/err.js:30

### ISSUE THREAD

**Issue by jeanvetorello** [john-titor-master/bombcrypto-superbot#11]
Boa tarde,

Bot está caindo mais vezes de acordo com o erro abaixo.

/bombcrypto-superbot/build/err.js:30
    return new SuperBotException(type, `${type}: ${message}`);
           ^

SuperBotException: MessageError: Failed with code 1005
    at makeException (/bombcrypto-superbot/build/err.js:30:12)
    at Client.handleMessageError (/bombcrypto-superbot/build/api/client.js:488:47)
    at Client.handleExtentionResponse (/bombcrypto-superbot/build/api/client.js:543:25)
    at t.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:6:38057)
    at e.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:24112)
    at t.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:94887)
    at t.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:6:38057)
    at WebSocket.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:20672)
    at WebSocket.onMessage (/bombcrypto-superbot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (events.js:400:28) {
  type: 'MessageError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.17

**Comment by john-titor-master** [comment]
Acabei de subir um novo fix.
