### ISSUE TITLE
stuck in loggin in after yarn go command

### ISSUE THREAD

**Issue by alegalati123** [john-titor-master/bombcrypto-superbot#15]
![yarn go](https://user-images.githubusercontent.com/96633555/158930449-1ed801b2-cf7d-4e08-9288-0b11ab5567ce.png)

stuck in loggin after inicial yarn go command (Brasileiro)
POde me ajudar? Obrigado!

**Comment by ghost** [comment]
Boa noite, @alegalati123

O servidores do bomb estão desde as 8h da manhã do dia 17 com problemas.

As vezes conecta, porém, cai logo em seguida. 

Temos que aguardar eles resolverem

**Comment by alegalati123** [comment]
Era o server mesmo, agora está funcionando! Muito obrigado!!

Alguém sabe me dizer como ativar o telegram em multiaccount? tem que ser 1 bot para cada conta?

**Comment by rmmarconi** [comment]
2022-03-18T12:48:04.855Z [info]: Starting telegraf...
2022-03-18T12:48:04.861Z [info]: Logging in...
/bombcrypto-superbot/build/err.js:30
    return new SuperBotException(type, `${type}: ${message}`);
           ^

SuperBotException: LoginFailed: Error code 101
    at makeException (/bombcrypto-superbot/build/err.js:30:12)
    at Client.handleLoginError (/bombcrypto-superbot/build/api/client.js:307:91)
    at t.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:6:38057)
    at e.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:88417)
    at e.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:68919)
    at e.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:65729)
    at t.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:94887)
    at t.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:6:38057)
    at WebSocket.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:20672)
    at WebSocket.onMessage (/bombcrypto-superbot/node_modules/ws/lib/event-target.js:199:18) {
  type: 'LoginFailed'
}
