### ISSUE TITLE
Last update error

### ISSUE THREAD

**Issue by Mozez20** [john-titor-master/bombcrypto-superbot#17]
After git pull I have this error that was not there before

```
2022-03-20T18:29:30.045Z [info]: Logging in...
/root/bombcrypto-superbot/build/err.js:30
    return new SuperBotException(type, `${type}: ${message}`);
           ^
SuperBotException: LoginFailed: Error code 10
    at makeException (/root/bombcrypto-superbot/build/err.js:30:12)
    at Client.handleLoginError (/root/bombcrypto-superbot/build/api/client.js:318:91)
    at t.value (/root/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:6:38057)
    at e.value (/root/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:88417)
    at e.value (/root/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:68919)
    at e.value (/root/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:65729)
    at t.value (/root/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:94887)
    at t.value (/root/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:6:38057)
    at WebSocket.value (/root/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:20672)
    at WebSocket.onMessage (/root/bombcrypto-superbot/node_modules/ws/lib/event-target.js:199:18) {
  type: 'LoginFailed'
}
error Command failed with exit code 1.
```

Also noticed you have removed MAX_WORKING_HEROES variable, do you think it's a better strategy?

**Comment by Mozez20** [comment]
I already found where the error was and it was my mistake.

What do you think about the strategy of using the heroes 5 by 5?
This was giving me very good results, I'm not sure if sending all at the same time is better but surely you have more experience than me in the game and have noticed that this new way is more profitable.

**Comment by john-titor-master** [comment]
Originally, the strategy of 5 at a time made sense. But since the bombs are placed at optimal places, there is not need anymore for rotation of heroes. This way, the bot will wait till the hero has at least 20 HP and will send it to work again.

**Comment by alegalati123** [comment]
> I already found where the error was and it was my mistake.
> 
> What do you think about the strategy of using the heroes 5 by 5? This was giving me very good results, I'm not sure if sending all at the same time is better but surely you have more experience than me in the game and have noticed that this new way is more profitable.

im havig the same error after this last update, how did you fix it?

thx!!

**Comment by Mozez20** [comment]
The error was mine because the file that launches the bot did not contain the wallet_id, it was not related to the project itself or the update.
