### ISSUE TITLE
Conseguiram logar no novo sistema? aqui tenho o seguinte erro:

### ISSUE THREAD

**Issue by alegalati123** [john-titor-master/bombcrypto-superbot#46]
Estou tendo erro tanto no login pelo usuário quanto pela private key:

2022-04-12T14:16:14.982Z [info]: Starting telegraf...
2022-04-12T14:16:14.984Z [info]: Logging in...
/bombcrypto-superbot/build/err.js:30
    return new SuperBotException(type, `${type}: ${message}`);
           ^

SuperBotException: LoginFailed: Error code 101
    at makeException (/bombcrypto-superbot/build/err.js:30:12)
    at Client.handleLoginError (/bombcrypto-superbot/build/api/client.js:346:91)
    at t.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:6:38057)
    at e.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:88417)
    at e.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:68919)
    at e.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:65729)
    at t.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:94887)
    at t.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:6:38057)
    at WebSocket.value (/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:20672)
    at WebSocket.onMessage (/bombcrypto-superbot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/bombcrypto-superbot/node_modules/ws/lib/websocket.js:1093:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/bombcrypto-superbot/node_modules/ws/lib/receiver.js:507:14)
    at /bombcrypto-superbot/node_modules/ws/lib/receiver.js:473:23
    at /bombcrypto-superbot/node_modules/ws/lib/permessage-deflate.js:308:9 {
  type: 'LoginFailed'

**Comment by Manowgu** [comment]
NOME=user:login:senha TELEGRAM= yarn go

**Comment by alegalati123** [comment]
erro:


yarn run v1.22.17
$ yarn lint && yarn format:check && yarn build && yarn start
$ eslint src/ --ext .ts
$ yarn prettier --check src/
$ C:\Users\Alega\Desktop\bombcrypto-superbot\node_modules\.bin\prettier --check src/
Checking formatting...
All matched files use Prettier code style!
$ tsc
src/api/client.ts(9,17): error TS2307: Cannot find module 'got' or its corresponding type declarations.
src/api/requests.ts(2,18): error TS2307: Cannot find module 'web3' or its corresponding type declarations.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dilneiss** [comment]
Aqui tbm não rola: LOGIN=user:dilnei:minhasenha yarn go
Sempre pede wallet_id

**Comment by xclover0** [comment]
**yarn install** <---- to update the modules

then 

LOGIN=user:user:pass yarn go

**Comment by alegalati123** [comment]
the yarn actually updated but still got the same error

**Comment by zomanuniverse** [comment]
they updated to 41 and bot still 40

**Comment by alegalati123** [comment]
just did a git pull and yarn update and now it is working!

**Comment by alegalati123** [comment]
does anyone knows what changes need to be done in docker? to run infinite mode

**Comment by zomanuniverse** [comment]
> does anyone knows what changes need to be done in docker? to run infinite mode

you mean this 
docker run --env-file=1.env --restart=always --name bsb1 -dt bsb

**Comment by alegalati123** [comment]
> > does anyone knows what changes need to be done in docker? to run infinite mode
> 
> you mean this docker run --env-file=1.env --restart=always --name bsb1 -dt bsb

yes this one!  but how about the ".env" file, how does it have to be? i tried the user:password and didnt work. Thx!!

**Comment by zomanuniverse** [comment]
you need to create user and password then use it on env file like : 
LOGIN=alegalati123:123123

**Comment by alegalati123** [comment]
Only works without docker, i tried to create all types of env files =/
LOGIN=user:user:password
LOGIN=user:password

etc..

**Comment by zomanuniverse** [comment]
i don't know why i feel that you didn't create scholar in Bcrypto

**Comment by alegalati123** [comment]
i did, the line LOGIN=user:user:password TELEGRAM_KEY=xxxxxxxxx yarn go is working fine outside docker, but im doing something wrong for sure
