### ISSUE TITLE
Error after second run

### ISSUE THREAD

**Issue by jianwei87** [john-titor-master/bombcrypto-superbot#57]
I get this error after i did the second run 

2022-04-19T09:47:52.786Z [info]: Starting telegraf...
2022-04-19T09:47:52.788Z [info]: Logging in...
C:\Users\JW\Desktop\crypto\bombcrypto-superbot\build\err.js:30
    return new SuperBotException(type, `${type}: ${message}`);
           ^

SuperBotException: ConnectionFailed: Connection failed
    at makeException (C:\Users\JW\Desktop\crypto\bombcrypto-superbot\build\err.js:30:12)
    at Client.handleConnection (C:\Users\JW\Desktop\crypto\bombcrypto-superbot\build\api\client.js:339:97)
    at t.value (C:\Users\JW\Desktop\crypto\bombcrypto-superbot\node_modules\sfs2x-api\sfs2x-api-1.7.15.js:6:38057)
    at t.value (C:\Users\JW\Desktop\crypto\bombcrypto-superbot\node_modules\sfs2x-api\sfs2x-api-1.7.15.js:7:94587)
    at t.value (C:\Users\JW\Desktop\crypto\bombcrypto-superbot\node_modules\sfs2x-api\sfs2x-api-1.7.15.js:6:38057)
    at WebSocket.value (C:\Users\JW\Desktop\crypto\bombcrypto-superbot\node_modules\sfs2x-api\sfs2x-api-1.7.15.js:7:20209)
    at WebSocket.onClose (C:\Users\JW\Desktop\crypto\bombcrypto-superbot\node_modules\ws\lib\event-target.js:210:18)
    at WebSocket.emit (node:events:526:28)
    at WebSocket.emitClose (C:\Users\JW\Desktop\crypto\bombcrypto-superbot\node_modules\ws\lib\websocket.js:245:12)
    at Object.onceWrapper (node:events:645:28)
    at ClientRequest.emit (node:events:526:28)
    at emitAbortNT (node:_http_client:377:7)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'ConnectionFailed'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tholakk** [comment]
where admin?

**Comment by gohun0096** [comment]
V 43

**Comment by alegalati123** [comment]
how do we get V 43? thx!!
