### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by yokosogithub** [john-titor-master/bombcrypto-superbot#62]
2022-04-24T07:13:31.675Z [info]: Starting telegraf...
2022-04-24T07:13:31.678Z [info]: Logging in...
/Users/rabo/Desktop/bombcrypto-superbot/build/err.js:30
    return new SuperBotException(type, `${type}: ${message}`);
           ^

SuperBotException: LoginFailed: Error code 101
    at makeException (/Users/rabo/Desktop/bombcrypto-superbot/build/err.js:30:12)
    at Client.handleLoginError (/Users/rabo/Desktop/bombcrypto-superbot/build/api/client.js:346:91)
    at t.value (/Users/rabo/Desktop/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:6:38057)
    at e.value (/Users/rabo/Desktop/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:88417)
    at e.value (/Users/rabo/Desktop/bombcrypto-superbot/node_modules/sfs2x-api/sfs2x-api-1.7.15.js:7:68919)

**Comment by waelsy123** [comment]
Checkout my fork

**Comment by yokosogithub** [comment]
> Checkout my fork

Same issue.
SuperBotException: LoginFailed: Error code 101

**Comment by ghost** [comment]
> 

what happens if i activate adventure mode? being that it is deprecated

**Comment by lucasvieceli** [comment]
https://t.me/bombcryptoFreeBot

**Comment by waelsy123** [comment]
you can use my fork, I keep maintaining it with new updates https://github.com/waelsy123/bombcrypto-superbot

**Comment by ghost** [comment]
> you can use my fork, I keep maintaining it with new updates https://github.com/waelsy123/bombcrypto-superbot

I've been using it for 2 days, thank you very much.
