### ISSUE TITLE
Alive fork 

### ISSUE THREAD

**Issue by waelsy123** [john-titor-master/bombcrypto-superbot#67]
As the developer is busy and there are no other maintainers, feel free to use my fork as I keep maintaining it https://github.com/waelsy123/bombcrypto-superbot

**Comment by ghost** [comment]
C:\Users\Weslley\Downloads\bombcrypto-superbot-master\build\err.js:30
    return new SuperBotException(type, `${type}: ${message}`);
           ^

SuperBotException: MissingEnv: Enviroment variable 'PORT' is missing.
    at makeException (C:\Users\Weslley\Downloads\bombcrypto-superbot-master\build\err.js:30:12)
    at requireEnv (C:\Users\Weslley\Downloads\bombcrypto-superbot-master\build\lib.js:47:39)
    at C:\Users\Weslley\Downloads\bombcrypto-superbot-master\build\index.js:21:43
    at Generator.next (<anonymous>)
    at C:\Users\Weslley\Downloads\bombcrypto-superbot-master\build\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Weslley\Downloads\bombcrypto-superbot-master\build\index.js:4:12)
    at main (C:\Users\Weslley\Downloads\bombcrypto-superbot-master\build\index.js:19:12)
    at Object.<anonymous> (C:\Users\Weslley\Downloads\bombcrypto-superbot-master\build\index.js:50:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  type: 'MissingEnv'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ghost** [comment]
I just downloaded and gave yarn install and got this error

**Comment by waelsy123** [comment]
Add another env variable before yarn go, for instance: 

PORT=3001 LOGIN=xxxx yarn go

**Comment by zomanuniverse** [comment]
is they still banning people who use this bot ?

**Comment by ghost** [comment]
> is they still banning people who use this bot ?

I've been using it for 3 days and I haven't been banned yet

**Comment by KxFxN** [comment]
Excuse me, how do I set the energy percentage for sending heroes?  and how to choose a hero to enter the house Or is there a way to write a config file?

**Comment by ghost** [comment]
> As the developer is busy and there are no other maintainers, feel free to use my fork as I keep maintaining it https://github.com/waelsy123/bombcrypto-superbot

are you going to fix adventure mode?

**Comment by waelsy123** [comment]
Not in the near future

**Comment by KxFxN** [comment]
> Not in the near future

@[waelsy123](https://github.com/waelsy123)

![image](https://user-images.githubusercontent.com/58837369/167186961-e776324a-5f24-4785-9674-70da9424467a.png)


**Why can't I login after server update?**

**Comment by waelsy123** [comment]
Just pushed a fix

**Comment by lucasvieceli** [comment]
I checked how it's done in the bot, to throw the bombs. I saw that he was dropping a bomb, waiting for the server to return to then throw another bomb,

I'm corrected so he can throw the amount of bombs according to his rarity and also respecting the hero's time to go to the place to burst the bomb, so a super legendary will now be able to throw the 6 bombs at once. just like it's done on the official website

it's still in test phase



then I will publish the changes in my repository, in case you want to put them in your @waelsy123

**Comment by waelsy123** [comment]
thanks @lucasvieceli! I like your changes, I have been pulling it to my fork regularly
